// LOCALHOST
### Get all contacts
GET http://localhost:8080/contacts

### Get a contact by ID
GET http://localhost:8080/contacts/68ddf84961d42baa133ded4d


### Add a new contact  - POST
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Buchi",
  "lastName": "Mentu",
  "email": "bucciment@example.com",
  "favoriteColor": "Mangetta",
  "birthday": "10/20/1992"
}

### Update a contact - PUT
PUT http://localhost:8080/contacts/68ddf84961d42baa133ded4d

{
  "firstName": "Buchi",
  "lastName": "Mentu",
  "email": "bucciment@example.com",
  "favoriteColor": "Grey",
  "birthday": "10/20/2005"
}

### Delete a contact
DELETE http://localhost:8080/contacts/68ddf84961d42baa133ded4d
Content-Type: application/json



// PRODUCTION 
### Get all contacts - GET ALL
GET https://three41-project-bzcd.onrender.com/contacts

### Get a contact by ID - GET SINGLE
GET https://three41-project-bzcd.onrender.com/contacts/68d96e70ffd7a727745d2127
### Add a new contact  - POST
POST https://three41-project-bzcd.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Ada",
  "lastName": "Okoro",
  "email": "adaokoro@example.com",
  "favoriteColor": "Green",
  "birthday": "1990-07-20"
}

### Update a contact - PUT
PUT https://three41-project-bzcd.onrender.com/contacts/68d77a50dcb5ca97997ac4f5
Content-Type: application/json

{
  "firstName": "Ada",
  "lastName": "Okoro",
  "email": "adaokoro@example.com",
  "favoriteColor": "Green",
  "birthday": "1990-07-20"
}

### Delete a contact
DELETE https://three41-project-bzcd.onrender.com/contacts/68d96e70ffd7a727745d2127
Content-Type: application/json